---
title: "Demand for labour"
output: html_notebook
---


```{r}
library(tidyverse)
library(readxl)
library(fst)
```

List sheets

```{r}
excel_sheets("../data-raw/z51_tabw00.xlsx")
```

Tables with information about vacancies -- 2018 I quarter


```{r}
read_excel(path = "../data-raw/z51_tabw00.xlsx",
                        sheet = "t15", skip = 11,
                        col_names = c("occup", "total", LETTERS[1:19])) %>%
  filter(str_detect(occup, "^6", negate = T)) %>%
  filter(str_detect(occup, "^\\d{2}", negate = T)) %>%
  select(-total) %>%
  gather(nace, vacc, -occup) %>%
  mutate(nace = ifelse(nace %in% c("A", "B", "D", "E", "K", "L", "P", "R", "S"), "other", nace)) %>%
  count(occup, nace, wt = vacc, name = "jvs") %>%
  mutate(occup = str_extract(occup, "\\d{1}")) -> occup_pkd

occup_pkd 
```

```{r}
saveRDS(object = occup_pkd, file = "../data/df-demand-totals.rds")
```


Read "big data" register data


```{r}
cbop2018 <- read_fst("~/git/zbiory/cbop/cbop2018_df.fst")

cbop2018 %>%
  mutate(data_waz_do = lubridate::ymd(data_waz_do),
         data_waz_od = lubridate::ymd(data_waz_od),
         data_archiw = lubridate::ymd(data_archiw),
         liczba_miejsc_og = as.numeric(liczba_miejsc_og)) %>%
  filter(data_waz_od <= as.Date("2018-03-31"), 
         data_waz_do > as.Date("2018-03-31"),
         data_archiw > as.Date("2018-03-31"),
         substr(kod_zawodu, 1,1) != "6", 
         waluta == "Złoty",
         liczba_miejsc_og > 0, 
         !kod_rodz_zatrud %in% c("Nie dotyczy", "Umowa o dzieło", "Umowa zlecenie / Umowa o świadczenie usług",
                                 "Wybór", "Powołanie", "Mianowanie"))  %>%
  mutate(wyksztalcenie = str_detect(inne_wymagania, "wykszt|Wyksz|wyk\\.|wyk "),
         wyksz_wyzsze = str_detect(inne_wymagania, "wyższe|Wyższe|magister|licencjat|doktor"),
         wyksz_zawod = str_detect(inne_wymagania, "zawodowe"),
         jezyk = str_detect(inne_wymagania, "język|jezyk")) -> cbop_2018_1

cbop_2018_1 
  count(kod_syst_wynagr, wt = liczba_miejsc_og) %>%
  add_count(wt = n, name = "total") %>%
  mutate(p = n/total*100)
  filter(kod_syst_wynagr %in% c("Czasowy ze stawką godzinową", "Czasowy ze stawką miesięczną")) %>%
  xtabs(n ~ zawod + kod_syst_wynagr, data = .) 
```

